version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Installing Maven...
      - mvn -version
  pre_build:
    commands:
      - echo Pre-build phase...
      - mvn clean
  build:
    commands:
      - echo Build started on `date`
      - mvn package -DskipTest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/**/*.jar
  discard-paths: yes